baseURL: 'https://sofijacom.github.io/'
languageCode: 'en-us'
- theme: 'hugo-simple'
remote_theme: pages-themes/merlot@v0.2.0
title: 'Kennel Linux'
description: 'Bookmark this to keep an eye on my project updates!'
