baseURL = 'https://sofijacom.github.io/'
languageCode = 'en-us'
title = 'Kennel Linux'
theme = 'hugo-simple'

[params]
hideRSSLink = true

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Links"
pageRef = "/links"
weight = 20
