name = "hugo-catppuccino"
license = "MIT"
licenselink = "https://gitlab.com/Romanizer/hugo-catppuccino/-/blob/master/LICENSE"
description = "A cute, responsive theme inspired by terminal ricing aesthetics."

homepage = "https://gitlab.com/Romanizer/hugo-catppuccino"
#demosite = "https://risotto.joeroe.io"

tags = ["responsive", "dark mode", "cute"]
features = []

[author]
  name = "Roman Hayn"
  homepage = "https://romanslab.net"

